export const NetworkListMock = [
  {
    uniqueId: 'test Data',
    serviceType: 'MCI',
    group: 'MCI#1',
    channelId: '123.132.',
    serviceNodeName: '노드1',
    transmitQueue: 123,
    receiveQueue: 123,
    numberOfCloseWait: 123,
    links: 123,
    port: 123,
    sourceLinks: 3,
    destLinks: 3,
  },
  {
    uniqueId: 'test Data',
    serviceType: 'FEP',
    group: 'FEP#1',
    channelId: '123.132.',
    serviceNodeName: '노드1',
    transmitQueue: 123,
    receiveQueue: 123,
    numberOfCloseWait: 123,
    links: 123,
    port: 123,
    sourceLinks: 3,
    destLinks: 3,
  },
  {
    uniqueId: 'test Data',
    serviceType: 'FEP',
    group: 'FEP#1',
    channelId: '123.132.',
    serviceNodeName: '노드1',
    transmitQueue: 123,
    receiveQueue: 123,
    numberOfCloseWait: 123,
    links: 123,
    port: 123,
    sourceLinks: 3,
    destLinks: 3,
  },
  {
    uniqueId: 'test Data',
    serviceType: 'EAI',
    group: 'EAI#1',
    channelId: '123.132.',
    serviceNodeName: '노드1',
    transmitQueue: 123,
    receiveQueue: 123,
    numberOfCloseWait: 123,
    links: 123,
    port: 123,
    sourceLinks: 3,
    destLinks: 3,
  },
  {
    uniqueId: 'test Data',
    serviceType: 'EAI',
    group: 'EAI#1',
    channelId: '123.132.',
    serviceNodeName: '노드1',
    transmitQueue: 123,
    receiveQueue: 123,
    numberOfCloseWait: 123,
    links: 123,
    port: 123,
    sourceLinks: 3,
    destLinks: 3,
  },
  {
    uniqueId: 'test Data',
    serviceType: 'MCI',
    group: 'MCI#1',
    channelId: '123.132.',
    serviceNodeName: '노드1',
    transmitQueue: 123,
    receiveQueue: 123,
    numberOfCloseWait: 123,
    links: 123,
    port: 123,
    sourceLinks: 3,
    destLinks: 3,
  },
  {
    uniqueId: 'test Data',
    serviceType: 'MCI',
    group: 'MCI#1',
    channelId: '123.132.',
    serviceNodeName: '노드1',
    transmitQueue: 123,
    receiveQueue: 123,
    numberOfCloseWait: 123,
    links: 123,
    port: 123,
    sourceLinks: 3,
    destLinks: 3,
  },
  {
    uniqueId: 'test Data',
    serviceType: 'MCI',
    group: 'MCI#1',
    channelId: '123.132.',
    serviceNodeName: '노드1',
    transmitQueue: 123,
    receiveQueue: 123,
    numberOfCloseWait: 123,
    links: 123,
    port: 123,
    sourceLinks: 3,
    destLinks: 3,
  },
];

export const NetworkDetailListMock = [
  {
    sourcePort: 5,
    sourceIP: 'test Data',
    targetIP: 'test Data',
    targetPort: 5,
    tcpState: 'test Data',
    transmitQueue: 5,
    receiveQueue: 5,
  },
  {
    sourcePort: 5,
    sourceIP: 'test Data',
    targetIP: 'test Data',
    targetPort: 5,
    tcpState: 'test Data',
    transmitQueue: 5,
    receiveQueue: 5,
  },
  {
    sourcePort: 5,
    sourceIP: 'test Data',
    targetIP: 'test Data',
    targetPort: 5,
    tcpState: 'test Data',
    transmitQueue: 5,
    receiveQueue: 5,
  },
];
