export const TopologyNodeMock = [
  {
    id: 'A',
    type: 'groupNode',
    data: { label: null },
    position: { x: 0, y: 0 },
    style: {
      width: 350,
      height: 850,
      borderRadius: 20,
      backgroundColor: '#637381',
    },
  },
  {
    id: 'A-T',
    type: 'selectorNode',
    data: { title: '대내 채널그룹', data: [] },
    position: { x: 25, y: 10 },
    parentNode: 'A',
    style: {
      backgroundColor: 'transparent',
      border: 'none',
      color: 'white',
    },
  },
  {
    id: 'A1',
    type: 'selectorNode',
    data: {
      label: '',
      data: [
        {
          name: 'MCI배치',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
        {
          name: '비대면',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
        {
          name: '이기종',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
      ],
    },
    position: { x: 25, y: 60 },
    parentNode: 'A',
  },
  {
    id: 'A2',
    type: 'selectorNode',
    data: {
      label: '',
      data: [
        {
          name: 'MCI배치',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
        {
          name: '비대면',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
        {
          name: '이기종',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
      ],
    },
    position: { x: 25, y: 260 },
    parentNode: 'A',
  },
  {
    id: 'A3',
    type: 'selectorNode',
    data: {
      label: '',
      data: [
        {
          name: 'MCI배치',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
        {
          name: '비대면',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
        {
          name: '이기종',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
      ],
    },
    position: { x: 25, y: 460 },
    parentNode: 'A',
  },
  {
    id: 'A4',
    type: 'selectorNode',
    data: {
      label: '',
      data: [
        {
          name: 'MCI배치',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
        {
          name: '비대면',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
        {
          name: '이기종',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
      ],
    },
    position: { x: 25, y: 660 },
    parentNode: 'A',
  },
  {
    id: 'B',
    type: 'groupNode',
    data: { label: null },
    position: { x: 400, y: 0 },
    style: {
      width: 350,
      height: 850,
      borderRadius: 20,
      backgroundColor: '#637381',
    },
  },
  {
    id: 'B-T',
    type: 'selectorNode',
    data: { title: 'MCI', data: [] },
    position: { x: 25, y: 10 },
    style: {
      backgroundColor: 'transparent',
      border: 'none',
      color: 'white',
    },
    parentNode: 'B',
  },
  {
    id: 'B1',
    type: 'selectorNode',
    data: {
      label: 'MCI#1',
      type: 'column',
      data: [
        {
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
      ],
    },
    position: { x: 25, y: 60 },
    parentNode: 'B',
  },
  {
    id: 'B2',
    type: 'selectorNode',
    data: {
      label: 'MCI#2',
      type: 'column',
      data: [
        {
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
      ],
    },
    position: { x: 25, y: 260 },
    parentNode: 'B',
  },
  {
    id: 'B3',
    type: 'selectorNode',
    data: {
      label: 'MCI#3',
      type: 'column',
      data: [
        {
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
      ],
    },
    position: { x: 25, y: 460 },
    parentNode: 'B',
  },
  {
    id: 'B4',
    type: 'selectorNode',
    data: {
      label: 'MCI#4',
      type: 'column',
      data: [
        {
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
      ],
    },
    position: { x: 25, y: 660 },
    parentNode: 'B',
  },
  {
    id: 'C',
    data: { label: null },
    type: 'groupNode',
    position: { x: 800, y: 0 },
    style: {
      width: 350,
      height: 250,
      borderRadius: 20,
      backgroundColor: '#637381',
    },
  },
  {
    id: 'C-T',
    type: 'selectorNode',
    data: {
      title: 'NexCore',
      data: [],
    },
    position: { x: 25, y: 10 },
    style: {
      backgroundColor: 'transparent',
      border: 'none',
      color: 'white',
    },
    parentNode: 'C',
  },
  {
    id: 'C1',
    type: 'selectorNode',
    data: {
      label: 'dopos21',
      type: 'chart',
      data: [],
    },
    position: { x: 25, y: 60 },
    parentNode: 'C',
  },

  {
    id: 'D',
    data: { label: null },
    type: 'groupNode',
    position: { x: 1200, y: 0 },
    style: {
      width: 350,
      height: 850,
      borderRadius: 20,
      backgroundColor: '#637381',
    },
  },
  {
    id: 'D-T',
    type: 'selectorNode',
    data: { title: 'FEP', data: [] },
    position: { x: 25, y: 10 },
    style: {
      backgroundColor: 'transparent',
      border: 'none',
      color: 'white',
    },
    parentNode: 'D',
  },
  {
    id: 'D1',
    type: 'selectorNode',
    data: {
      label: 'FEP#1',
      type: 'column',
      data: [
        {
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
      ],
    },
    position: { x: 25, y: 60 },
    parentNode: 'D',
  },
  {
    id: 'D2',
    type: 'selectorNode',
    data: {
      label: 'FEP#2',
      type: 'column',
      data: [
        {
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
      ],
    },
    position: { x: 25, y: 260 },
    parentNode: 'D',
  },
  {
    id: 'D3',
    type: 'selectorNode',
    data: {
      label: 'FEP#3',
      type: 'column',
      data: [
        {
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
      ],
    },
    position: { x: 25, y: 460 },
    parentNode: 'D',
  },
  {
    id: 'D4',
    type: 'selectorNode',
    data: {
      label: 'FEP#4',
      type: 'column',
      data: [
        {
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
      ],
    },
    position: { x: 25, y: 660 },
    parentNode: 'D',
  },
  {
    id: 'E',
    type: 'groupNode',
    data: { label: null },
    position: { x: 1600, y: 0 },
    style: {
      width: 350,
      height: 850,
      borderRadius: 20,
      backgroundColor: '#637381',
    },
  },
  {
    id: 'E-T',
    type: 'selectorNode',
    data: { title: '대내 채널그룹', data: [] },
    position: { x: 25, y: 10 },
    style: {
      backgroundColor: 'transparent',
      border: 'none',
      color: 'white',
    },
    parentNode: 'E',
  },
  {
    id: 'E1',
    type: 'selectorNode',
    data: {
      label: '',
      data: [
        {
          name: 'MCI배치',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
        {
          name: '비대면',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
        {
          name: '이기종',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
      ],
    },
    position: { x: 25, y: 60 },
    parentNode: 'E',
  },
  {
    id: 'E2',
    type: 'selectorNode',
    data: {
      label: '',
      data: [
        {
          name: 'MCI배치',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
        {
          name: '비대면',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
        {
          name: '이기종',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
      ],
    },
    position: { x: 25, y: 260 },
    parentNode: 'E',
  },
  {
    id: 'E3',
    type: 'selectorNode',
    data: {
      label: '',
      data: [
        {
          name: 'MCI배치',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
        {
          name: '비대면',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
        {
          name: '이기종',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
      ],
    },
    position: { x: 25, y: 460 },
    parentNode: 'E',
  },
  {
    id: 'E4',
    type: 'selectorNode',
    data: {
      label: '',
      data: [
        {
          name: 'MCI배치',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
        {
          name: '비대면',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
        {
          name: '이기종',
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
      ],
    },
    position: { x: 25, y: 660 },
    parentNode: 'E',
  },
  {
    id: 'F',
    data: { label: null },
    type: 'groupNode',
    position: { x: 800, y: 300 },
    style: {
      width: 350,
      height: 450,
      borderRadius: 20,
      backgroundColor: '#637381',
    },
  },
  {
    id: 'F-T',
    type: 'selectorNode',
    data: { title: 'EAI', data: [] },
    position: { x: 25, y: 10 },
    style: {
      backgroundColor: 'transparent',
      border: 'none',
      color: 'white',
    },
    parentNode: 'F',
  },
  {
    id: 'F1',
    type: 'selectorNode',
    data: {
      label: 'EAI#1',
      type: 'column',
      data: [
        {
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
      ],
    },
    position: { x: 25, y: 60 },
    parentNode: 'F',
  },
  {
    id: 'F2',
    type: 'selectorNode',
    data: {
      label: 'EAI#2',
      type: 'column',
      data: [
        {
          catution: '5',
          warning: '2',
          danger: '3',
          critical: '3',
        },
      ],
    },
    position: { x: 25, y: 260 },
    parentNode: 'F',
  },
];

export const TopologyEdgesMock = [
  {
    id: '1',
    source: 'A1',
    target: 'B1',
    sourceHandle: '3',
    animated: true,
    style: { stroke: '#1890FF', strokeWidth: 15 },
  },
  {
    id: '2',
    source: 'A2',
    target: 'B2',
    sourceHandle: '3',
    animated: true,
    style: { stroke: '#1890FF', strokeWidth: 15 },
  },
  {
    id: '3',
    source: 'A3',
    target: 'B3',
    sourceHandle: '3',
    animated: true,
    style: { stroke: '#1890FF', strokeWidth: 15 },
  },
  {
    id: '4',
    source: 'A4',
    target: 'B4',
    sourceHandle: '3',
    animated: true,
    style: { stroke: '#1890FF', strokeWidth: 15 },
  },
  {
    id: '5',
    source: 'E1',
    target: 'D1',
    targetHandle: '4',
    animated: true,
    style: { stroke: '#1890FF', strokeWidth: 15 },
  },
  {
    id: '6',
    source: 'E2',
    target: 'D2',
    targetHandle: '4',
    animated: true,
    style: { stroke: '#1890FF', strokeWidth: 15 },
  },
  {
    id: '7',
    source: 'E3',
    target: 'D3',
    targetHandle: '4',
    animated: true,
    style: { stroke: '#1890FF', strokeWidth: 15 },
  },
  {
    id: '8',
    source: 'E4',
    target: 'D4',
    targetHandle: '4',
    animated: true,
    style: { stroke: '#1890FF', strokeWidth: 15 },
  },
  {
    id: '9',
    source: 'B1',
    target: 'C1',
    sourceHandle: '3',
    animated: true,
    style: { stroke: '#1890FF', strokeWidth: 15 },
  },
  {
    id: '10',
    source: 'D1',
    target: 'C1',
    targetHandle: '4',
    animated: true,
    style: { stroke: '#1890FF', strokeWidth: 15 },
  },

  {
    id: '17',
    source: 'F',
    target: 'C',
    sourceHandle: '5',
    targetHandle: '8',
    animated: true,
    style: { stroke: '#1890FF', strokeWidth: 15 },
  },
];
